name: Building

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    checking:
        name: Build check & Packaging correctly
        runs-on: ubuntu-latest

        permissions:
            contents: read
            security-events: write
            actions: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Dependencies check
              run: npm i

            - name: Building
              shell: bash
              run: npx rbxtsc --verbose

            - name: Done
              run: |
                  echo done
